### PR TITLE
added fn to get headers and to add custom header

### PR DESCRIPTION
**Pull request by bmurphy333**

### CODE REVIEW

**Comment by JCrawsh** [comment]
@bmurphy333 Pushed a commit up to make sure X-API-Key or X-API-Secret headers can't be changed

**Review by JCrawsh — APPROVED** [review]
LGTM

**Comment by bmurphy333** [comment]
Should we return an error if they try to reset the key and secret headers?

**Comment by JCrawsh** [comment]
It would be safer and I suppose its only a minor change

**Review by JCrawsh — APPROVED** [review]
LGTM

**Pull request merged**
