### PR TITLE
Wip restructure services

### PR DESCRIPTION
**Pull request by JCrawsh**
Restructured the different elements of the client into their own services.

### CODE REVIEW

**Comment by bmurphy333** [comment]
are we not going to be moving the models objects into their service package?

**Comment by JCrawsh** [comment]
Potentially at some point but that change doesn't prevent us from merging this one in.

**Comment by bmurphy333** [comment]
yeah sure, theres a few other bit we need to do before the restructure is done anyway. All looks good though, can discuss more later. I'm ok to merge - but might be good to wait till we're together to go over with Josh

**Review by joshwalong — APPROVED** [review]
lgtm

**Review by bmurphy333 — APPROVED** [review]
lgtm

**Pull request merged**
